### ISSUE TITLE
is it possible / difficult to decouple the vue front-end and have it be standalone ?

### ISSUE THREAD

**Issue by vesper8** [jcc/blog#166]
I'm looking to intergrate a blog in my vue-cli front-end site which interacts with a Laravel installation strictly through API, consider them to be on separate servers.

Is PJ suited for this? It may not work out of the box but would it be very hard to use the Vue components and stick them on a standalone site and then fetch the posts content through a Rest API? Including for editing/adding posts.. or is this completely out of scope for this project?

So many good CMSs based on Laravel that make use of Vue but it seems none of them are decoupled

**Comment by jcc** [comment]
Sorry, PJ is not suited for this. Because CMSs provide installer for installing that everyone can use it easily. Of course you can try to build the front-end site by `@vue-cli` and provide Laravel APIs. I recommend an open source site for you.

Front-end: https://github.com/overtrue/yike.io
Back-end: https://github.com/overtrue/api.yike.io

If you have any problems, you can send emails for me.
