### ISSUE TITLE
Article content

### ISSUE THREAD

**Issue by wayson** [jcc/blog#61]
Article 表的content里面夹杂了html和markdown，如果再建一个字段分别存放这两个内容的话，可以用solr来做full text search。

**Comment by jcc** [comment]
这种改数据结构的在大版本升级再考虑。
发自网易邮箱大师
在2017年06月09日 15:00，wayson 写道： Article 表的content里面夹杂了html和markdown，如果再建一个字段分别存放这两个内容的话，可以用solr来做full text search。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jcc/blog","title":"jcc/blog","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jcc/blog"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Article content (#61)"}],"action":{"name":"View Issue","url":"https://github.com/jcc/blog/issues/61"}}}
